### ISSUE TITLE
임의의 파일 가능하게

### ISSUE THREAD

**Issue by jyshoon** [dhtnekfzz/-#1]
- 지금은 "abc.txt"만 암호화가 됨
- 임의의 파일이름을 입력 받아서, 
  그 파일을 암호화하여
  "파일이름.enc" 파일로 저장

**Comment by dhtnekfzz** [comment]
임이의 파일을 암호화하여 s.enc파일로 저장한다.

**Comment by dhtnekfzz** [comment]
char filename[100];
printf ("Enter file name : ");
scanf ("%s", filename);
fopen함수에 filename으로 파일이름 사용

**Comment by dhtnekfzz** [comment]
프로그램에서 파일명을 입력받아 파일을 생성하여 파일을 암호화하고 저장할 파일의 이름을 입력받고 입력받은 이름으로 암호화된 새로운 파일을 저장한다.
